# Windows host service configuration
host_id: "2e53e7f6-1417-4531-a5eb-23dee63d261e"
host_token: "763c5345ce872e066fbe38cced59828a19f4afba8214db1c4e8ab7046d6eb11b"
port: 8443
default_shell: "powershell"
tls_cert_path: "../certs/host.crt"
tls_key_path: "../certs/host.key"
relay_url: "wss://localhost:8443"
discovery:
  enabled: true
  service_name: "_rtx._tcp"
  friendly_name: "Development Host"
pty:
  initial_cols: 120
  initial_rows: 30
  buffer_size: 8192
log_level: "info"
auto_register_devices: true